-- 숏츠 테이블 생성
CREATE TABLE IF NOT EXISTS shorts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  video_id TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  creator TEXT NOT NULL,
  channel_id TEXT NOT NULL DEFAULT '',
  types TEXT NOT NULL DEFAULT '[]',
  maps TEXT NOT NULL DEFAULT '[]',
  thumbnail TEXT,
  published_at TEXT,
  crawled_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_shorts_channel ON shorts(channel_id);
CREATE INDEX IF NOT EXISTS idx_shorts_crawled ON shorts(crawled_at DESC);

-- 기존 정적 데이터 시드
INSERT OR IGNORE INTO shorts (video_id, title, creator, types, maps, thumbnail) VALUES
('6eF-3adI5s0','B2연구소 딱 1분만 집중해서 배워봐!!','위폭연구소장','["꿀팁"]','[]','https://i.ytimg.com/vi/6eF-3adI5s0/hqdefault.jpg'),
('A90yX1GuZck','총 안쏘고 토너먼트 우승하는 법','위폭연구소장','["꿀팁"]','[]','https://i.ytimg.com/vi/A90yX1GuZck/hqdefault.jpg'),
('d4Thxenc9Oc','서든 방패들면 뭐하냐고~','위폭연구소장','["하이라이트"]','[]','https://i.ytimg.com/vi/d4Thxenc9Oc/hqdefault.jpg'),
('nkNGRlCpkVU','머리에서 숏녹 폭 쉽게 던지는 법','위폭연구소장','["위폭"]','["머리"]','https://i.ytimg.com/vi/nkNGRlCpkVU/hqdefault.jpg'),
('0kEVBxAPdRE','서든 혼자서 6초만에 게임 끝내기','위폭연구소장','["하이라이트"]','[]','https://i.ytimg.com/vi/0kEVBxAPdRE/hqdefault.jpg'),
('fGcqr_M7Wa8','녹위 혼자서 쉽게 올라가는 방법','위폭연구소장','["꿀팁"]','["녹위"]','https://i.ytimg.com/vi/fGcqr_M7Wa8/hqdefault.jpg'),
('mM-z0DYE2Mc','랭크전 4800구간 모두가 놀란 세이브','위폭연구소장','["세이브","랭크전"]','[]','https://i.ytimg.com/vi/mM-z0DYE2Mc/hqdefault.jpg'),
('k9cYXNY4rR8','랭크전 4400구간 올킬세이브','위폭연구소장','["세이브","랭크전"]','[]','https://i.ytimg.com/vi/k9cYXNY4rR8/hqdefault.jpg'),
('RjIU2lc6DmE','나만의 감도를 쉽게 찾는 법','위폭연구소장','["꿀팁"]','[]','https://i.ytimg.com/vi/RjIU2lc6DmE/hqdefault.jpg'),
('g_KhqQyYlSA','패스폭 대기 자리 쉽게 잡는 법','위폭연구소장','["위폭","꿀팁"]','[]','https://i.ytimg.com/vi/g_KhqQyYlSA/hqdefault.jpg'),
('B_XufHs8hRE','랭크전 랭킹 1·2등 유지하는 법','위폭연구소장','["꿀팁","랭크전"]','[]','https://i.ytimg.com/vi/B_XufHs8hRE/hqdefault.jpg'),
('fsAddYtSVgc','머리에서 쓰리깡 폭 쉽게 던지는 법','위폭연구소장','["위폭"]','["머리"]','https://i.ytimg.com/vi/fsAddYtSVgc/hqdefault.jpg'),
('6LfwsTyR3Ys','컨 사이 폭 쉽게 던지는 법','위폭연구소장','["위폭"]','[]','https://i.ytimg.com/vi/6LfwsTyR3Ys/hqdefault.jpg'),
('NwI6wJm6uf4','삼박 개구리 쉽게 잡는법 (카운터)','위폭연구소장','["꿀팁"]','["삼박자"]','https://i.ytimg.com/vi/NwI6wJm6uf4/hqdefault.jpg'),
('lv19AI3RhXE','녹뒤폭 쉽게 던지는법','위폭연구소장','["위폭"]','["녹위"]','https://i.ytimg.com/vi/lv19AI3RhXE/hqdefault.jpg'),
('jJTGPw3KmeU','3미리 쉽게 잡는법','위폭연구소장','["꿀팁"]','["삼박자"]','https://i.ytimg.com/vi/jJTGPw3KmeU/hqdefault.jpg'),
('BTUU0o71MjY','삼박 개구리 쉽게 잡는법','위폭연구소장','["꿀팁"]','["삼박자"]','https://i.ytimg.com/vi/BTUU0o71MjY/hqdefault.jpg'),
('pC8tV2MtS2E','머리폭 쉽게 던지는법','위폭연구소장','["위폭"]','["머리"]','https://i.ytimg.com/vi/pC8tV2MtS2E/hqdefault.jpg'),
('k6bWXw_-E2Y','레드 옥상 쉽게 가는법 (1탄)','위폭연구소장','["꿀팁"]','["레드"]','https://i.ytimg.com/vi/k6bWXw_-E2Y/hqdefault.jpg'),
('BcZfY6_riMI','3깡 버닝 쉽게 하는법','위폭연구소장','["꿀팁"]','["삼박자"]','https://i.ytimg.com/vi/BcZfY6_riMI/hqdefault.jpg'),
('lUkyI0ebFWE','랭커구간 정확신속 카이팅','위폭연구소장','["꿀팁","랭크전"]','[]','https://i.ytimg.com/vi/lUkyI0ebFWE/hqdefault.jpg'),
('rBtyuhkUk9A','랭킹1등 내 설 내가 지켜','위폭연구소장','["하이라이트","랭크전"]','[]','https://i.ytimg.com/vi/rBtyuhkUk9A/hqdefault.jpg'),
('lszJvS51PTI','챔스 맴버들 사이에서 세이브','강혜준','["세이브"]','[]','https://i.ytimg.com/vi/lszJvS51PTI/hqdefault.jpg'),
('rAFNm7zwUw0','시티캣 A설대 다이나','강혜준','["하이라이트"]','["시티캣"]','https://i.ytimg.com/vi/rAFNm7zwUw0/hqdefault.jpg'),
('kWkxteQ1eJM','4vs1 세이브 10초면 충분해','강혜준','["세이브"]','[]','https://i.ytimg.com/vi/kWkxteQ1eJM/hqdefault.jpg'),
('XypI4v75rnI','팀원들 모두가 외쳤다. 유하~','강혜준','["하이라이트","랭크전"]','[]','https://i.ytimg.com/vi/XypI4v75rnI/hqdefault.jpg'),
('-4DFC4flSOs','클랜간판전 16킬 캐리','강혜준','["하이라이트"]','[]','https://i.ytimg.com/vi/-4DFC4flSOs/hqdefault.jpg'),
('SNuRr7aIctg','올킬 세이브','텐시','["세이브"]','[]','https://i.ytimg.com/vi/SNuRr7aIctg/hqdefault.jpg'),
('JRskqhGqQ3o','5보급 필승전략 위폭','텐시','["위폭"]','["5보급"]','https://i.ytimg.com/vi/JRskqhGqQ3o/hqdefault.jpg'),
('AKYkXjDGWvA','이게 텐시다!!','텐시','["하이라이트"]','[]','https://i.ytimg.com/vi/AKYkXjDGWvA/hqdefault.jpg'),
('_WaC1BFhDWk','짧고 강렬한 세이브','텐시','["세이브"]','[]','https://i.ytimg.com/vi/_WaC1BFhDWk/hqdefault.jpg'),
('BpzPlxhTTMw','프로즌시티 월샷','텐시','["월샷"]','["프로즌시티"]','https://i.ytimg.com/vi/BpzPlxhTTMw/hqdefault.jpg'),
('QfyDfMMDNvc','시작하자마자 올킬 가능? 가능.','텐시','["하이라이트"]','[]','https://i.ytimg.com/vi/QfyDfMMDNvc/hqdefault.jpg'),
('axL6JsEPk28','시티켓 다이나','샷오바장인','["위폭"]','["시티캣"]','https://i.ytimg.com/vi/axL6JsEPk28/hqdefault.jpg'),
('fZ9X3ZG3VgA','크포 개방 작업폭','샷오바장인','["위폭"]','["크로스파이어"]','https://i.ytimg.com/vi/fZ9X3ZG3VgA/hqdefault.jpg'),
('bDxTUJUrCVo','이탈리아 머나먼 월샷(막힘)','샷오바장인','["월샷"]','["이탈리아"]','https://i.ytimg.com/vi/bDxTUJUrCVo/hqdefault.jpg'),
('NO_vQK_n4M8','마베 스위치 2층 폭 대기','샷오바장인','["위폭"]','["마베"]','https://i.ytimg.com/vi/NO_vQK_n4M8/hqdefault.jpg'),
('YsDrNNMaep0','트리오 삼거리 버그폭','샷오바장인','["위폭"]','["트리오"]','https://i.ytimg.com/vi/YsDrNNMaep0/hqdefault.jpg'),
('XAIZy9S2bHY','5보급 B 입구 폭','샷오바장인','["위폭"]','["5보급"]','https://i.ytimg.com/vi/XAIZy9S2bHY/hqdefault.jpg'),
('elGOArrjUws','프방 A/B 빠른 백업폭','샷오바장인','["위폭"]','["프로방스"]','https://i.ytimg.com/vi/elGOArrjUws/hqdefault.jpg'),
('BPp5FCIDhlQ','데저트 쌍문 레베 / A숏 야자 위폭','샷오바장인','["위폭"]','["데저트"]','https://i.ytimg.com/vi/BPp5FCIDhlQ/hqdefault.jpg'),
('GAGuh5CX7zU','프방 블베 / A숏아래 위폭','샷오바장인','["위폭"]','["프로방스"]','https://i.ytimg.com/vi/GAGuh5CX7zU/hqdefault.jpg'),
('ofMRZDogyVw','데저트 A숏 야자 뒤 위폭','샷오바장인','["위폭"]','["데저트"]','https://i.ytimg.com/vi/ofMRZDogyVw/hqdefault.jpg'),
('bX33_Lxy7yE','펠리스 B부대 앞/뒤 폭','샷오바장인','["위폭"]','["펠리스"]','https://i.ytimg.com/vi/bX33_Lxy7yE/hqdefault.jpg'),
('0Bh6rsMjDaw','화콜 A설대 위폭 모음','샷오바장인','["위폭"]','["화콜"]','https://i.ytimg.com/vi/0Bh6rsMjDaw/hqdefault.jpg'),
('NIEajozElMY','화콜 천막 밑 멸망폭','샷오바장인','["위폭"]','["화콜"]','https://i.ytimg.com/vi/NIEajozElMY/hqdefault.jpg'),
('FUCxi_1QbZc','화콜 센숏 버그폭','샷오바장인','["위폭"]','["화콜"]','https://i.ytimg.com/vi/FUCxi_1QbZc/hqdefault.jpg'),
('g5mOUjQcl1g','프방 B설대에서 위폭 2개','샷오바장인','["위폭"]','["프로방스"]','https://i.ytimg.com/vi/g5mOUjQcl1g/hqdefault.jpg'),
('nSip6fjK2vY','화콜 물방 입구 폭 5개','샷오바장인','["위폭"]','["화콜"]','https://i.ytimg.com/vi/nSip6fjK2vY/hqdefault.jpg'),
('-6HOY19Tu3E','크포 위치 체크 2(혈흔)','샷오바장인','["꿀팁"]','["크로스파이어"]','https://i.ytimg.com/vi/-6HOY19Tu3E/hqdefault.jpg'),
('rNDvcnM163w','데저트 A센스나 박스 위폭','샷오바장인','["위폭"]','["데저트"]','https://i.ytimg.com/vi/rNDvcnM163w/hqdefault.jpg'),
('P5eE52HfCVg','데저트2 신전 1층 폭','샷오바장인','["위폭"]','["데저트"]','https://i.ytimg.com/vi/P5eE52HfCVg/hqdefault.jpg'),
('wfVaBn1hqWY','펠리스 B롱 섬광 2가지','샷오바장인','["위폭"]','["펠리스"]','https://i.ytimg.com/vi/wfVaBn1hqWY/hqdefault.jpg'),
('np-vEonfEtQ','프방 A 광역 섬광','샷오바장인','["위폭"]','["프로방스"]','https://i.ytimg.com/vi/np-vEonfEtQ/hqdefault.jpg'),
('yrs8WU8Fqw4','올드타운 언더 위폭','샷오바장인','["위폭"]','["올드타운"]','https://i.ytimg.com/vi/yrs8WU8Fqw4/hqdefault.jpg'),
('Ec4PlfFaE6M','프로방스 우유통 위폭','샷오바장인','["위폭"]','["프로방스"]','https://i.ytimg.com/vi/Ec4PlfFaE6M/hqdefault.jpg'),
('rKY2CZTP-nU','이탈리아 발코니 폭 2개','샷오바장인','["위폭"]','["이탈리아"]','https://i.ytimg.com/vi/rKY2CZTP-nU/hqdefault.jpg'),
('PRcgawpZMYw','올타 B진입로 위폭(레베)','샷오바장인','["위폭"]','["올드타운"]','https://i.ytimg.com/vi/PRcgawpZMYw/hqdefault.jpg'),
('ZLCcSKBHXGU','말릴 때 이렇게 해보세요','샷오바장인','["꿀팁"]','[]','https://i.ytimg.com/vi/ZLCcSKBHXGU/hqdefault.jpg'),
('mrMujlDWmh8','런어인의 폭탄 해체 방법','샷오바장인','["꿀팁"]','[]','https://i.ytimg.com/vi/mrMujlDWmh8/hqdefault.jpg'),
('QALfTdfqu0s','우유통 틈','victor','["하이라이트"]','["프로방스"]','https://i.ytimg.com/vi/QALfTdfqu0s/hqdefault.jpg'),
('LV7qd_bb2gI','양각 처리','victor','["꿀팁"]','[]','https://i.ytimg.com/vi/LV7qd_bb2gI/hqdefault.jpg'),
('su4GPZ7P7Bs','순서가 있어','victor','["꿀팁"]','[]','https://i.ytimg.com/vi/su4GPZ7P7Bs/hqdefault.jpg'),
('T-jYXbSp4ps','데저트 A백업','victor','["꿀팁"]','["데저트"]','https://i.ytimg.com/vi/T-jYXbSp4ps/hqdefault.jpg'),
('1BNat9Alw3g','A뚫','victor','["하이라이트"]','[]','https://i.ytimg.com/vi/1BNat9Alw3g/hqdefault.jpg'),
('uLKj8VjY1Hk','클랭 올킬','victor','["하이라이트"]','[]','https://i.ytimg.com/vi/uLKj8VjY1Hk/hqdefault.jpg'),
('SSw7PlKnYtk','통했나','victor','["하이라이트"]','[]','https://i.ytimg.com/vi/SSw7PlKnYtk/hqdefault.jpg'),
('dnRdeIuNQiA','아다리 낚시','victor','["꿀팁"]','[]','https://i.ytimg.com/vi/dnRdeIuNQiA/hqdefault.jpg'),
('e-k1za-Php8','심리전','victor','["꿀팁"]','[]','https://i.ytimg.com/vi/e-k1za-Php8/hqdefault.jpg'),
('EZT8moYcDEE','DRT','victor','["하이라이트"]','[]','https://i.ytimg.com/vi/EZT8moYcDEE/hqdefault.jpg'),
('NGLWCeW58G8','어택중에도 미니맵','victor','["꿀팁"]','[]','https://i.ytimg.com/vi/NGLWCeW58G8/hqdefault.jpg'),
('IIVCPIYzERg','좋은 브리핑','victor','["꿀팁"]','[]','https://i.ytimg.com/vi/IIVCPIYzERg/hqdefault.jpg'),
('74nhcfoZwis','10년동안 위폭 연구만 했던 유저','lafo','["위폭"]','[]','https://i.ytimg.com/vi/74nhcfoZwis/hqdefault.jpg'),
('guAoiNvulvE','월샷만 15년째 쏘는 유저의 플레이','lafo','["월샷"]','[]','https://i.ytimg.com/vi/guAoiNvulvE/hqdefault.jpg'),
('844mRXORHqw','무빙없어도 다 잡는 유저','lafo','["하이라이트"]','[]','https://i.ytimg.com/vi/844mRXORHqw/hqdefault.jpg'),
('b-tAFaS0Zpw','절대 안 보이는 엇각 자리에서 킬하기','lafo','["꿀팁"]','[]','https://i.ytimg.com/vi/b-tAFaS0Zpw/hqdefault.jpg'),
('xtLkmigGr2A','빼꼼하면서 잡는 꿀팁 3가지','lafo','["꿀팁"]','[]','https://i.ytimg.com/vi/xtLkmigGr2A/hqdefault.jpg'),
('XaTPMFxKmCs','100년만에 나온 매드무비','lafo','["하이라이트"]','[]','https://i.ytimg.com/vi/XaTPMFxKmCs/hqdefault.jpg'),
('VpunnvQ4Iv0','말 그대로 벽을 보는중인 적 팀','lafo','["하이라이트"]','[]','https://i.ytimg.com/vi/VpunnvQ4Iv0/hqdefault.jpg'),
('N83Iasw38HY','한 번쯤은 만나본 랭크전 빌런','lafo','["랭크전"]','[]','https://i.ytimg.com/vi/N83Iasw38HY/hqdefault.jpg'),
('lGYxiPc_mrQ','월샷으로 게임하는 1인칭 시점','lafo','["월샷"]','[]','https://i.ytimg.com/vi/lGYxiPc_mrQ/hqdefault.jpg'),
('Qq957mNHkVw','1티어 라플 스카 소음기 vs 노소음기','라포','["무기리뷰"]','[]','https://i.ytimg.com/vi/Qq957mNHkVw/hqdefault.jpg'),
('7NGjY5zDz_g','랭크전에 써먹기 좋은 1티어 샵건','라포','["무기리뷰","랭크전"]','[]','https://i.ytimg.com/vi/7NGjY5zDz_g/hqdefault.jpg'),
('MwqRJizfdpU','서든어택의 근본, 스나는 아직도 좋은가?','라포','["무기리뷰"]','[]','https://i.ytimg.com/vi/MwqRJizfdpU/hqdefault.jpg'),
('TZdUfz125Qs','손 풀고 첫 라운드에 나온 깔끔한 플레이','라포','["하이라이트"]','[]','https://i.ytimg.com/vi/TZdUfz125Qs/hqdefault.jpg'),
('gGR2vwdKFTg','넓은 맵에서 줌만 쏘면 핵공격 되는 1티어 라플','라포','["무기리뷰"]','[]','https://i.ytimg.com/vi/gGR2vwdKFTg/hqdefault.jpg'),
('IesXH-K8tkA','현 시점 전구간에서 쓰는 1티어 라플','라포','["무기리뷰"]','[]','https://i.ytimg.com/vi/IesXH-K8tkA/hqdefault.jpg'),
('_g3BRfgbWKQ','사기 신규 12세트 동글이 AWX','라포','["무기리뷰"]','[]','https://i.ytimg.com/vi/_g3BRfgbWKQ/hqdefault.jpg'),
('4N1c69HgPYc','제일 비싼 윈체 써봤습니다','라포','["무기리뷰"]','[]','https://i.ytimg.com/vi/4N1c69HgPYc/hqdefault.jpg'),
('0S_ysfbvcDY','앞만 보면 안되는 이유 ㅋㅋ','라포','["꿀팁"]','[]','https://i.ytimg.com/vi/0S_ysfbvcDY/hqdefault.jpg'),
('I2dcZWawVBs','뛰어다니면서 B 혼자 막아주는 스나','라포','["월샷"]','[]','https://i.ytimg.com/vi/I2dcZWawVBs/hqdefault.jpg'),
('tjFk9E1Oc1o','쓰기 어렵지만 잘쓰면 사기 총','라포','["무기리뷰"]','[]','https://i.ytimg.com/vi/tjFk9E1Oc1o/hqdefault.jpg'),
('Sy2RdDfZMQo','핵처럼 보이는 관통 샷','라포','["월샷"]','[]','https://i.ytimg.com/vi/Sy2RdDfZMQo/hqdefault.jpg'),
('2tjSgp4Es1w','한번씩 쓰면 무조건 통하는 기술','라포','["꿀팁"]','[]','https://i.ytimg.com/vi/2tjSgp4Es1w/hqdefault.jpg'),
('hLZv6wx2TWM','랭크전 고스트폭이 1티어인 이유','라포','["위폭","랭크전"]','[]','https://i.ytimg.com/vi/hLZv6wx2TWM/hqdefault.jpg'),
('nRxKbNpDpDE','해체할때만 쓸 수 있는 스네이크 기술','라포','["꿀팁"]','[]','https://i.ytimg.com/vi/nRxKbNpDpDE/hqdefault.jpg'),
('P8ntFZqlf4Q','생존모드 무조건 챙겨야 할 총 1위','라포','["무기리뷰"]','[]','https://i.ytimg.com/vi/P8ntFZqlf4Q/hqdefault.jpg'),
('a617o8qZ4QE','스프레이 활용하기','라포','["꿀팁"]','[]','https://i.ytimg.com/vi/a617o8qZ4QE/hqdefault.jpg'),
('zLcd0YB6VgM','공격수 세이브','라포','["세이브"]','[]','https://i.ytimg.com/vi/zLcd0YB6VgM/hqdefault.jpg'),
('JUvMk9Anz5k','반샷의 장점','라포','["꿀팁"]','[]','https://i.ytimg.com/vi/JUvMk9Anz5k/hqdefault.jpg');
