
import React, { useState, useEffect, useMemo } from 'react';
import { useApp } from '../state/AppContext';
import { useUI } from '../state/UIContext';
import { marked } from 'marked';
import { ModeStat } from '../types';

const StatBox: React.FC<{ label: string, value: number, suffix?: string }> = ({ label, value, suffix = '' }) => {
    return (
        <div className="bg-white/60 backdrop-blur-md p-3 rounded-2xl border border-white/60 text-center flex flex-col items-center justify-center h-full shadow-sm hover:shadow-md transition-shadow">
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-tight">{label}</span>
            <span className="text-xl font-black text-slate-900 mt-1">{value.toFixed(1)}{suffix}</span>
        </div>
    );
};

const ResultView: React.FC<{ stat: ModeStat }> = ({ stat }) => (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-2 duration-500">
        {/* Summary Header */}
        <div className="text-center bg-slate-50/50 p-4 rounded-2xl border border-white/50">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-widest">Selected Match Analysis</span>
            <div className="text-lg font-black text-slate-800 mt-2 mb-4">{stat.modeName}</div>
            
            <div className="text-5xl font-black text-slate-900 drop-shadow-sm">{stat.matchCount} Matches</div>
            
            <div className="grid grid-cols-2 gap-4 mt-6">
                <StatBox label="Win Rate" value={stat.winRate} suffix="%" />
                <StatBox label="K/D Rate" value={stat.kd} suffix="%" />
            </div>
        </div>

        {stat.aiAnalysis && (
            <div className="bg-slate-50 rounded-2xl p-5 border border-slate-100 shadow-sm relative">
                <div className="flex items-center gap-2 mb-3">
                    <span className="w-2 h-2 bg-cyan-500 rounded-full animate-pulse"></span>
                    <span className="text-[10px] font-black text-cyan-600 uppercase tracking-widest">AI_Tactical_Feedback</span>
                </div>
                {/* 
                   Prose styling with specific overrides for strong tags to ensure bold text is visible 
                   [&_strong]: targets <strong> tags generated by marked
                */}
                <div 
                    className="text-xs text-slate-600 font-medium leading-relaxed prose prose-sm max-w-none 
                               [&_strong]:text-slate-900 [&_strong]:font-black [&_strong]:bg-cyan-50 [&_strong]:px-1 [&_strong]:rounded"
                    dangerouslySetInnerHTML={{ __html: marked.parse(stat.aiAnalysis) as string }}
                />
            </div>
        )}
    </div>
);

export const RecapModal: React.FC = () => {
  const { isRecapModalOpen, closeRecapModal } = useUI();
  const { calculateRecap, recapStats, isRecapLoading, userProfile } = useApp();
  
  const getTodayKST = () => {
    const now = new Date();
    const utc = now.getTime() + (now.getTimezoneOffset() * 60000);
    const kst = new Date(utc + (9 * 60 * 60 * 1000)); 
    return kst.toISOString().split('T')[0];
  };

  const [selectedDate, setSelectedDate] = useState(getTodayKST());
  const [selectedType, setSelectedType] = useState('');
  const [selectedMode, setSelectedMode] = useState('');

  // 1. 날짜가 변경되면 해당 날짜의 매치들을 스캔하여 가능한 Type (상위) 목록 생성
  // 이제 matchType에는 "폭파미션" 등이 들어옵니다.
  const availableTypes = useMemo(() => {
      if (!userProfile) return [];
      const dateMatches = userProfile.recentMatches.filter(m => m.rawDate.startsWith(selectedDate));
      const types = Array.from(new Set(dateMatches.map(m => m.matchType)));
      return types;
  }, [userProfile, selectedDate]);

  // 2. Type이 선택되면 해당 Type 내의 가능한 Mode (하위) 목록 생성
  // 이제 matchMode에는 "랭크전 솔로" 등이 들어옵니다.
  const availableModes = useMemo(() => {
      if (!userProfile || !selectedType) return [];
      const dateMatches = userProfile.recentMatches.filter(m => m.rawDate.startsWith(selectedDate));
      const modes = Array.from(new Set(dateMatches.filter(m => m.matchType === selectedType).map(m => m.matchMode)));
      return modes;
  }, [userProfile, selectedDate, selectedType]);

  // Reset selection when options change
  useEffect(() => {
      if (availableTypes.length > 0 && !availableTypes.includes(selectedType)) {
          setSelectedType(availableTypes[0]);
      } else if (availableTypes.length === 0) {
          setSelectedType('');
      }
  }, [availableTypes]);

  useEffect(() => {
      if (availableModes.length > 0 && !availableModes.includes(selectedMode)) {
          setSelectedMode(availableModes[0]);
      } else if (availableModes.length === 0) {
          setSelectedMode('');
      }
  }, [availableModes]);

  if (!isRecapModalOpen) return null;

  const handleAnalyze = () => {
    if (!selectedType || !selectedMode) return;
    calculateRecap(selectedDate, selectedType, selectedMode);
  };

  const handleDateClick = (e: React.MouseEvent<HTMLInputElement>) => {
      const input = e.currentTarget;
      try {
          if (typeof input.showPicker === 'function') {
              input.showPicker();
          } else {
              input.focus();
          }
      } catch (err) {
          console.warn("DatePicker open failed:", err);
          input.focus();
      }
  };

  return (
    <div className="fixed inset-0 z-[110] flex items-center justify-center bg-slate-900/60 backdrop-blur-md p-4 animate-in fade-in duration-300" onClick={closeRecapModal}>
      <div 
        className="w-full max-w-md bg-white/90 backdrop-blur-2xl rounded-3xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh] animate-in slide-in-from-bottom-5 duration-500 border border-white/50"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="bg-slate-900/95 p-6 text-white text-center flex-shrink-0 backdrop-blur-xl relative overflow-hidden">
             <div className="absolute top-[-50%] left-[-20%] w-[200px] h-[200px] bg-blue-500/20 rounded-full blur-3xl"></div>
             <div className="absolute bottom-[-50%] right-[-20%] w-[200px] h-[200px] bg-purple-500/20 rounded-full blur-3xl"></div>
            
            <h2 className="text-xl font-black uppercase tracking-tight relative z-10">Daily Match Report</h2>
            <p className="text-sm text-slate-400 mt-1 relative z-10">심층 매치 분석 (Deep Dive)</p>
        </div>

        <div className="p-6 overflow-y-auto space-y-6 overscroll-contain flex-1">
            {/* 설정 섹션 */}
            <div className="bg-white p-5 rounded-3xl border border-slate-100 shadow-sm space-y-5">
                
                {/* 1. Date */}
                <div>
                    <div className="flex justify-between items-center mb-2">
                        <label className="text-[10px] font-black text-slate-500 uppercase tracking-widest flex items-center gap-1">
                            <span>📅</span> Select Date
                        </label>
                        <button 
                            onClick={() => setSelectedDate(getTodayKST())}
                            className="text-[9px] font-bold text-blue-500 hover:text-blue-600 hover:underline transition-colors"
                        >
                            오늘
                        </button>
                    </div>
                    <input 
                        type="date" 
                        value={selectedDate}
                        onChange={(e) => setSelectedDate(e.target.value)}
                        onClick={handleDateClick}
                        className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl font-bold text-slate-900 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/20 transition-all cursor-pointer"
                    />
                </div>

                {availableTypes.length > 0 ? (
                    <>
                         {/* 2. Match Type (Upper Level) */}
                        <div>
                            <label className="text-[10px] font-black text-slate-500 uppercase tracking-widest block mb-2">
                                ⚔️ Match Type (게임 유형: 폭파미션 등)
                            </label>
                            <div className="relative">
                                <select 
                                    value={selectedType} 
                                    onChange={(e) => setSelectedType(e.target.value)}
                                    className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl font-bold text-slate-900 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/20 appearance-none"
                                >
                                    {availableTypes.map(t => <option key={t} value={t}>{t}</option>)}
                                </select>
                                <div className="absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none text-slate-400">
                                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" /></svg>
                                </div>
                            </div>
                        </div>

                        {/* 3. Match Mode (Lower Level) */}
                        <div>
                            <label className="text-[10px] font-black text-slate-500 uppercase tracking-widest block mb-2">
                                🎯 Match Mode (세부 모드: 랭크전 솔로 등)
                            </label>
                            <div className="relative">
                                <select 
                                    value={selectedMode} 
                                    onChange={(e) => setSelectedMode(e.target.value)}
                                    className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl font-bold text-slate-900 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/20 appearance-none"
                                >
                                    {availableModes.map(m => <option key={m} value={m}>{m}</option>)}
                                </select>
                                <div className="absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none text-slate-400">
                                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" /></svg>
                                </div>
                            </div>
                        </div>

                        {/* Analyze Button */}
                        <button 
                            onClick={handleAnalyze}
                            disabled={isRecapLoading || !selectedType || !selectedMode}
                            className="w-full py-4 bg-slate-900 hover:bg-slate-800 text-white font-black rounded-2xl shadow-lg disabled:opacity-50 transition-all active:scale-[0.98] whitespace-nowrap text-xs uppercase tracking-[0.2em] flex items-center justify-center gap-2"
                        >
                            {isRecapLoading ? (
                                <>
                                    <span className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin"></span>
                                    Deep Dive Analyzing...
                                </>
                            ) : (
                                <>
                                    <span>🔍</span> Run_Analysis
                                </>
                            )}
                        </button>
                    </>
                ) : (
                    <div className="p-4 bg-slate-50 rounded-xl border border-dashed border-slate-200 text-center">
                        <span className="text-xs text-slate-400 font-medium">선택한 날짜에 플레이 기록이 없습니다.</span>
                    </div>
                )}
            </div>

            {/* 결과 표시 Area */}
            {recapStats ? (
                <ResultView stat={recapStats.stat} />
            ) : (
                availableTypes.length > 0 && (
                    <div className="text-center py-8 text-slate-400 text-sm bg-slate-50/30 rounded-2xl border border-dashed border-slate-200">
                        <span className="block mb-2 text-2xl">👆</span>
                        분석할 모드와 유형을 선택해주세요.
                    </div>
                )
            )}
        </div>

        <div className="p-4 border-t border-slate-100/50 bg-white/50 backdrop-blur-md flex-shrink-0">
             <button onClick={closeRecapModal} className="w-full py-4 bg-white/80 border border-white text-slate-700 font-bold rounded-xl hover:bg-white transition-colors shadow-sm active:scale-98">
                닫기
             </button>
        </div>
      </div>
    </div>
  );
};
